### ISSUE TITLE
python package installation error

### ISSUE THREAD

**Issue by QuanWan89** [HanwenXuTHU/BioTranslatorProject#10]
`pip install biotranslator`

Collecting biotranslator
  Using cached biotranslator-0.1.2.tar.gz (32 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [16 lines of output]
      Traceback (most recent call last):
        File "/opt/py/conda/PyLib_Common/envs/biotranslator/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353
, in <module>
          main()
        File "/opt/py/conda/PyLib_Common/envs/biotranslator/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335
, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/opt/py/conda/PyLib_Common/envs/biotranslator/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118
, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-_vwnyd73/overlay/lib/python3.9/site-packages/flit_core/buildapi.py", line 23, in get_requires_for_build_wheel
          info = read_flit_config(pyproj_toml)
        File "/tmp/pip-build-env-_vwnyd73/overlay/lib/python3.9/site-packages/flit_core/config.py", line 79, in read_flit_config
          return prep_toml_config(d, path)
        File "/tmp/pip-build-env-_vwnyd73/overlay/lib/python3.9/site-packages/flit_core/config.py", line 106, in prep_toml_config
          loaded_cfg = read_pep621_metadata(d['project'], path)
        File "/tmp/pip-build-env-_vwnyd73/overlay/lib/python3.9/site-packages/flit_core/config.py", line 616, in read_pep621_metadata
          raise ConfigError(
      flit_core.config.ConfigError: flit only supports dynamic metadata for 'version' & 'description'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error
× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.
note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by HanwenXuTHU** [comment]
Hi Quan, 
Sorry for this error! We are working towards fixing this error but it might take some time. The main codes are already in this repo, I would recommend you start from this codebase first. If you meet any question, feel free to reach out to me.
